---
language: python
python: "2.7.13"
sudo: required

services:
  - docker
install:
  - pip install ansible==2.4.5.0
  - pip install molecule==2.19
  - pip install docker
script:
  - travis_wait 60 molecule test --driver docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
