---

- name: Azkaban | Download MySQL connector
  get_url:
    url: "{{ mysql_connector_url }}"
    dest: "/tmp/{{ mysql_connector_package }}"

- name: Azkaban | Extract MySQL connector
  unarchive:
    copy: no
    src: "/tmp/{{ mysql_connector_package }}"
    dest: "/tmp"

- include: config-executor.yml
  tags: azkaban-executor
  when: azkaban_server_role in ["executor", "all"]

- include: config-web.yml
  tags: azkaban-web
  when: azkaban_server_role in ["web", "all"]
