---

- name: Azkaban | Extract Azkaban executor server
  unarchive:
    copy: no
    src: "/tmp/{{ azkaban_version_build_name }}/azkaban-exec-server/build/distributions/azkaban-exec-server-{{ azkaban_server_version }}.zip"
    dest: "/opt"
    owner: "{{ azkaban_user }}"
    group: "{{ azkaban_group }}"
  when: azkaban_version_check|failed or azkaban_version_check.stdout != azkaban_version

- name: Azkaban | Symbolic link to latest Azkaban executor server
  file:
    src: "/opt/azkaban-exec-server-{{ azkaban_server_version }}"
    dest: "{{ azkaban_exec_server_install_dir }}"
    state: link
    force: yes
    owner: "{{ azkaban_user }}"
    group: "{{ azkaban_group }}"
  when: azkaban_version_check|failed or azkaban_version_check.stdout != azkaban_version

- name: Azkaban | Copy start scripts
  template:
    src: "executorserver/{{ item }}.j2"
    dest: /etc/default/{{ item }}
    mode: 0755
    owner: "{{ azkaban_user }}"
    group: "{{ azkaban_group }}"
  with_items:
    - "azkaban-executor-start.sh"
    - "azkaban-executor"
    - "azkaban-executor-stop.sh"

- name: Azkaban | Copy daemon scripts
  template:
    src: "executorserver/azkaban-executorserver.service.j2"
    dest: /lib/systemd/system/azkaban-executorserver.service
    mode: 0644
